// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNK3THaJ5emuu6W_fEGutscjyd9xtRxpY',
    appId: '1:277901837319:web:ebbf179da89a5c59c4d6a2',
    messagingSenderId: '277901837319',
    projectId: 'fir-authentication-app-c01a1',
    authDomain: 'fir-authentication-app-c01a1.firebaseapp.com',
    storageBucket: 'fir-authentication-app-c01a1.firebasestorage.app',
    measurementId: 'G-ZFG6P7LEPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tMIoDBlktlyHSTtV43K3G_ZJhQWQ9KQ',
    appId: '1:277901837319:android:d48d3f107a57b8f6c4d6a2',
    messagingSenderId: '277901837319',
    projectId: 'fir-authentication-app-c01a1',
    storageBucket: 'fir-authentication-app-c01a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvt4aNfVGjRNG2mFxVLfq7SRPeVGzw8g4',
    appId: '1:277901837319:ios:194c0a78f6115956c4d6a2',
    messagingSenderId: '277901837319',
    projectId: 'fir-authentication-app-c01a1',
    storageBucket: 'fir-authentication-app-c01a1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvt4aNfVGjRNG2mFxVLfq7SRPeVGzw8g4',
    appId: '1:277901837319:ios:194c0a78f6115956c4d6a2',
    messagingSenderId: '277901837319',
    projectId: 'fir-authentication-app-c01a1',
    storageBucket: 'fir-authentication-app-c01a1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNK3THaJ5emuu6W_fEGutscjyd9xtRxpY',
    appId: '1:277901837319:web:1f10f21780daa38ac4d6a2',
    messagingSenderId: '277901837319',
    projectId: 'fir-authentication-app-c01a1',
    authDomain: 'fir-authentication-app-c01a1.firebaseapp.com',
    storageBucket: 'fir-authentication-app-c01a1.firebasestorage.app',
    measurementId: 'G-TG2GMF5ELS',
  );
}
